### ISSUE TITLE
components indeling 

### ISSUE THREAD

**Issue by RukiyaTossou** [Hadil66/DRY-Fabrique-Qatar-Museums#2]
Atoms:  
- ticket button 
- Individuele filter buttons
-  Zoek button
-  Zoekbalk 

Molecule:  
-  De groep met filter buttons
- Zoekbalk met button

organism: 
-  Navbar
-  filter buttons & zoekbalk 

Template: 
-  infinite canvas (masonary layout)

Pages : 
- Home pagina

**Comment by Hadil66** [comment]
![image](https://github.com/user-attachments/assets/5c3488c5-fd1d-44ac-a658-a31c958e2a6d)
