### ISSUE TITLE
Kampvuursessie 

### ISSUE THREAD

**Issue by Hadil66** [Hadil66/DRY-Fabrique-Qatar-Museums#9]
# Hoe ging de samenwerking?
## Welke minpunten heb jij bij jezelf gezien bij de samenwerking?

**Comment by Hadil66** [comment]
## Wat ging er goed aan de samenwerking?  
In het begin was het niet helemaal duidelijk dat het om een samenwerking ging, maar we hebben dit goed opgepakt. We hebben uiteindelijk veel samengewerkt en elkaar geholpen.  

## Wat kan er beter?  
Vaker en sneller begrijpen wat er van ons verwacht wordt, en elkaar tussendoor beter op de hoogte houden van de voortgang. Daarnaast duidelijker communiceren over het mergen. We gingen er vanuit dat iedereen een pull request zou schrijven, maar dat gebeurde niet. Hierdoor hadden we uiteindelijk geen complete site, wat jammer was, zeker omdat het de bedoeling was om alles goed te mergen.  

## Welke verbeterpunten zie je bij jezelf in de samenwerking?  
Ik heb mijn team niet vaak genoeg op de hoogte gehouden van mijn werk. Dat had ik vaker moeten doen.  Ook vanaf het begin met het projectboard werken.

**Comment by EBok1** [comment]
## Wat ging er goed aan het samenwerken?
In het begin van de sprint was het de bedoeling om een eigen component te verbeteren. Hierin was er niet veel samenwerking aanwezig. Behalve onderling de componenten verdelen. We zijn gezamenlijk naar de opdrachtgever geweest om daar te werken. Hier hebben we wat tips gekregen. Als iemand ergens niet uitkomt, staan we er voor open om te helpen, dit is fijn. 

## Wat kan er beter? 
Het communiceren ging goed, maarr kan wel beter. We zijn duidelijk naar elkaar, maar moeten vaker vertellen waar we mee bezig zijn etc. zodat we duidelijk afspraken met elkaar kunnen maken. 

## Welke verbeterpunten zie je bij jezelf in de samenwerking? 
Ik moet duidelijker over waar ik mee bezig ben naar de rest van mijn team. Ik denk dat ik dit kan doen door iedere dag een update te geven(check-in/out) even kort op teams. 
Het projectboard moet ik meer gebruik van gaan maken, dit wordt vaak door een iemand ingevuld.
